export default {
    products: [
      {
        _id: '1',
        name: 'MRF Kashmir Willow Cricket Bat',
        category: 'Bats',
        image: '/img/mrf1.jpg',
        price: 1250,
        brand: 'MRF',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
      },
      {
        _id: '2',
        name: 'GM English Willow Cricket Bat',
        category: 'Bats',
        image: '/img/gm2.jpg',
        price: 1500,
        brand: 'GM',
        rating: 5,
        numReviews: 51,
        countInStock: 10,
      },
      {
        _id: '3',
        name: 'Nivia Cricket Tennis Ball',
        category: 'Balls',
        image: '/img/ten_nivia.jpg',
        price: 50,
        brand: 'Nivia',
        rating: 4,
        numReviews: 45,
        countInStock: 50,
      },
      {
        _id: '4',
        name: 'TON Kashmir Willow Cricket Bat',
        category: 'Bats',
        image: '/img/ton1.jpg',
        price: 950,
        brand: 'TON',
        rating: 3.5,
        numReviews: 198,
        countInStock: 15,
      },
      {
        _id: '5',
        name: 'Guru Cricket Tennis Ball',
        category: 'Balls',
        image: '/img/tennis_guru.jpg',
        price: 45,
        brand: 'Guru',
        rating: 4.0,
        numReviews: 89,
        countInStock: 40,
      },
      {
        _id: '6',
        name: 'SG English Willow Cricket Bat',
        category: 'Bats',
        image: '/img/sg1.jpg',
        price: 900,
        brand: 'SG',
        rating: 4.5,
        numReviews: 45,
        countInStock: 5,
      },
    ],
  };